apiVersion: keycloak.org/v1alpha1
kind: Keycloak
metadata:
  name: keycloak
  labels:
    app: sso
    test: sso
spec:
  instances: 2
  storageClassName: ocs-storagecluster-ceph-rbd
  extensions:
    - https://github.com/aerogear/keycloak-metrics-spi/releases/download/1.0.4/keycloak-metrics-spi-1.0.4.jar
  externalAccess:
    enabled: True
  multiAvailablityZones:
    enabled: True
  podDisruptionBudget:
    enabled: True
  keycloakDeploymentSpec:
    resources:
      requests:
        cpu: 2700m
        memory: 800Mi
      limits:
        cpu: 2700m
        memory: 800Mi
  postgresDeploymentSpec:
    resources:
      requests:
        cpu: 250m
        memory: 250Mi
      limits:
        cpu: 250m
        memory: 250Mi