---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: route-reencrypt-binding
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: route-reencrypt-role
subjects:
  - kind: ServiceAccount
    name: nifi-sa
    namespace: nifi
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: route-reencrypt-role
rules:
  - apiGroups:
      - ""
      - route.openshift.io
    resources:
      - routes
      - routes/custom-host
    verbs:
      - get
      - list
      - update
      - patch
