---
kind: Route
apiVersion: route.openshift.io/v1
metadata:
  labels:
    app: "nifi"
  name: nifi
spec:
  to:
    kind: Service
    name: nifi
    weight: 100
  port:
    targetPort: https
  tls:
    termination: reencrypt
    destinationCACertificate: |-
      -----BEGIN CERTIFICATE-----
      MIIDRTCCAi2gAwIBAgIKAX0VjGfsAAAAADANBgkqhkiG9w0BAQsFADAhMQ0wCwYD
      VQQLDAROSUZJMRAwDgYDVQQDDAduaWZpLWNhMB4XDTIxMTExMjE5MDc0MloXDTI0
      MDIxNTE5MDc0MlowITENMAsGA1UECwwETklGSTEQMA4GA1UEAwwHbmlmaS1jYTCC
      ASIwDQYJKoZIhvcNAQEBBQADggEPADCCAQoCggEBALZBJLQAhjqGm7co9IAb4laJ
      jaxs+GKu7Lnv3moZvzEPGmGo2zEdTQBmWmui1cZSpJaU1z++p4nSLH8huxT9Fc5/
      1vV+8tB262ZOp4Nb1TzAsAp0vemxe/snL1pYHotgvLQbd4gY0Za4YUDTj6p+CAkg
      iMXcpKB8yzowUx0yEBvSXoHeDzt3qn7ARq6imYFOA1NRnBeEQTbh2Jx9rfQE4rXL
      marK9Jzbb3AT3MSfcz7kKsZkLtPM/51OgHciXAYW1qxJqSTLtX5vfqnn8chzjr8f
      qqpFmGWyc71ln9EiXmIymm6uuWInk+Mvi4BSMqF1ko+5LP09O9wLwwZt9Ypby+UC
      AwEAAaN/MH0wDgYDVR0PAQH/BAQDAgH+MAwGA1UdEwQFMAMBAf8wHQYDVR0OBBYE
      FKBUBrvQsYrDDgO2cYmFzSfucHV2MB8GA1UdIwQYMBaAFKBUBrvQsYrDDgO2cYmF
      zSfucHV2MB0GA1UdJQQWMBQGCCsGAQUFBwMCBggrBgEFBQcDATANBgkqhkiG9w0B
      AQsFAAOCAQEAQ84BTLM3iEXRkfIEssSHmB2+NYdRuY7XGaMYlfuWcu3vtyA7dsuE
      jZ6rcxjnYr3kfn9MM9Q5PtaAX3hy+36anknZnxvrcYwnZwAOJR90PSob5wAvCVo1
      ZzxfUqHFsJlekBqh+T3O5s1xdoT8/tG2sxI1t/7oIDFUITQcgCSXKl2SpChqOFON
      iNMgSHmevIE0qowVVHsi63ojxAASgjaSsIxNvWvJIychi+r4kzxDrlHhSfuFiNfR
      6C1Jg807NETWFjo/aRQHnA/F98Spvcm83V2OdJONqfjY4QQL/rZDOdmkBRLGciYZ
      Gv7g+9qdjNBAExMmDcFsX/BP8aIB/yBXyw==
      -----END CERTIFICATE-----
      -----BEGIN CERTIFICATE-----
      MIIDrzCCApegAwIBAgIKAX0VjOF0AAAAADANBgkqhkiG9w0BAQsFADAhMQ0wCwYD
      VQQLDAROSUZJMRAwDgYDVQQDDAduaWZpLWNhMB4XDTIxMTExMjE5MDgxNFoXDTI0
      MDIxNTE5MDgxNFowRTENMAsGA1UECwwETklGSTE0MDIGA1UEAwwrbmlmaS0wLm5p
      ZmktaGVhZGxlc3MubmlmaS5zdmMuY2x1c3Rlci5sb2NhbDCCASIwDQYJKoZIhvcN
      AQEBBQADggEPADCCAQoCggEBAK4F55AfX+PAvO8kVeIHoSfFYh5+Cw0xT9XSRWRd
      EZUjOcluxzLnzPpisaMVMKWw8grq36r7fqMUg98zNJ6Ivd58tU4VRIRcnKQnV3iV
      femzLtizpynSRuwXjWVgQkN3U9nQpa0ocoTD8/QkckvGPIljVomRKXkUY3dBvuUo
      Vnqqps+cbGWXM6jILp9hRU4RXZKhEYci5Ds5H5CwJanRw0L10tqcu58W927Vn5Me
      mf1THO40fonbu7Kqa0lxLkIl89EUDZxtTSmHGegJ2MACplDPbL43+vmmXUh+zI4D
      MPrXOArbDFsGQO0xx5MIIDl14s2Pfrbap92jZomxkEam3n8CAwEAAaOBxDCBwTAd
      BgNVHQ4EFgQUDFtprKszxuIKTOsLM5i0CJNSAOUwHwYDVR0jBBgwFoAUoFQGu9Cx
      isMOA7ZxiYXNJ+5wdXYwDgYDVR0PAQH/BAQDAgP4MAkGA1UdEwQCMAAwHQYDVR0l
      BBYwFAYIKwYBBQUHAwIGCCsGAQUFBwMBMEUGA1UdEQQ+MDyCK25pZmktMC5uaWZp
      LWhlYWRsZXNzLm5pZmkuc3ZjLmNsdXN0ZXIubG9jYWyCDW5pZmkubmlmaS5zdmMw
      DQYJKoZIhvcNAQELBQADggEBAB4G76kFKHXG5LsXmej0lVKQz4RRGySwoFuh40jP
      7zo+cd4I6w5fODo16r6AVIIEkCIrzBJezTIWLinEl2fJDy9OFdM4Oc9BPe+FFegJ
      ExKX1zg8tKnJDZo6qzGVTyjwbsAti6kI2W0C2WGNGgkGyKoeffJ56wyenOsObdPF
      yUb+vngwhZCj3wGUL8OZB5Y4kz7QAqyjVamgSERsJpHdzQzg603T1Xkhw+2t//Ua
      QyNKYKGqhX99CZLh++l+KVsQxROL9uYMTsZDIbCUZvELmj0HjA8vn4mlzTX5aj/Y
      nAldeGgma+G7uOFsCklVSgZEwbTMNDSwDP1Ji4SR/jWOI4c=
      -----END CERTIFICATE-----
    insecureEdgeTerminationPolicy: Redirect
