---
kind: Route
apiVersion: route.openshift.io/v1
metadata:
  labels:
    app: "nifi"
  name: nifi
spec:
  to:
    kind: Service
    name: nifi
    weight: 100
  port:
    targetPort: https
  tls:
    termination: reencrypt
    insecureEdgeTerminationPolicy: Redirect
    destinationCACertificate: |-
      TO_BE_REPLACED
